/* The following code was generated by JFlex 1.4.3 on 3/29/15 12:39 PM */

package com.jotc.nsis;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.jotc.nsis.psi.NSISTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/29/15 12:39 PM from the specification file
 * <tt>/Users/Joe/Documents/IdeaProjects/NSIS_language_support/src/com/jotc/nsis/plugin/nsis.flex</tt>
 */
class NSISLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int WAITING_VALUE = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\16\0\4\0\1\3\1\5"+
    "\1\0\1\4\1\0\2\0\1\0\10\0\12\0\1\0\1\4\5\0"+
    "\32\6\1\0\1\0\2\0\1\0\1\0\32\6\4\0\41\0\2\0"+
    "\4\0\4\0\1\6\2\0\1\0\7\0\1\6\4\0\1\6\5\0"+
    "\27\6\1\0\7\6\30\6\1\0\10\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\2\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\2\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\2\6\1\6\1\6\1\6\1\6\3\6"+
    "\2\6\1\6\1\6\1\6\2\6\1\6\3\6\2\6\4\6\1\6"+
    "\2\6\1\6\3\6\3\6\2\6\1\6\2\6\1\6\1\6\1\6"+
    "\1\6\1\6\2\6\1\6\1\6\2\6\1\6\1\6\2\6\1\6"+
    "\3\6\1\6\1\6\1\6\2\6\3\6\1\6\7\6\1\6\2\6"+
    "\1\6\2\6\1\6\2\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\2\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\2\6\1\6\2\6"+
    "\1\6\1\6\3\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\4\6\31\0\162\6\4\0\14\6\16\0\5\6\11\0\1\6"+
    "\21\0\130\0\5\0\23\0\12\0\1\6\13\0\1\6\1\0\3\6"+
    "\1\0\1\6\1\0\2\6\1\6\21\6\1\0\11\6\43\6\1\0"+
    "\2\6\3\6\3\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\5\6\1\6\1\6\1\0"+
    "\1\6\1\6\2\6\1\6\4\0\60\6\60\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\0\4\0\3\0\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\2\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\0\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\2\0\1\6\1\6\6\0\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\41\0\46\6\2\0\1\6\7\0\47\6\11\0\21\0\1\0"+
    "\27\0\1\0\3\0\1\0\1\0\1\0\2\0\1\0\1\0\13\0"+
    "\33\6\5\0\3\6\15\0\4\0\14\0\6\0\13\0\32\6\5\0"+
    "\13\6\16\0\7\0\12\0\4\0\2\6\1\0\143\6\1\0\1\6"+
    "\10\0\1\0\6\0\2\6\2\0\1\0\4\0\2\6\12\0\3\6"+
    "\2\0\1\6\17\0\1\0\1\6\1\0\36\6\33\0\2\0\3\6"+
    "\60\0\46\6\13\0\1\6\u014f\0\3\0\66\6\2\0\1\0\1\6"+
    "\20\0\2\0\1\6\4\0\3\0\12\6\2\0\2\0\12\0\21\0"+
    "\3\0\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0"+
    "\1\6\3\0\4\6\2\0\1\0\1\6\7\0\2\0\2\0\2\0"+
    "\3\0\11\0\1\0\4\0\2\6\1\0\3\6\2\0\2\0\12\0"+
    "\2\6\2\0\15\0\3\0\1\0\6\6\4\0\2\6\2\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\2\6\1\0\2\6\2\0\1\0"+
    "\1\0\5\0\4\0\2\0\2\0\3\0\13\0\4\6\1\0\1\6"+
    "\7\0\14\0\3\6\14\0\3\0\1\0\11\6\1\0\3\6\1\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\0\1\6"+
    "\10\0\1\0\3\0\1\0\3\0\2\0\1\6\17\0\2\6\2\0"+
    "\2\0\12\0\1\0\1\0\17\0\3\0\1\0\10\6\2\0\2\6"+
    "\2\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\0"+
    "\1\6\6\0\3\0\2\0\2\0\3\0\10\0\2\0\4\0\2\6"+
    "\1\0\3\6\4\0\12\0\1\0\1\6\20\0\1\0\1\6\1\0"+
    "\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6\1\0"+
    "\2\6\3\0\2\6\3\0\3\6\3\0\10\6\1\0\3\6\4\0"+
    "\5\0\3\0\3\0\1\0\4\0\11\0\1\0\17\0\11\0\11\0"+
    "\1\0\7\0\3\0\1\0\10\6\1\0\3\6\1\0\27\6\1\0"+
    "\12\6\1\0\5\6\4\0\7\0\1\0\3\0\1\0\4\0\7\0"+
    "\2\0\11\0\2\6\4\0\12\0\22\0\2\0\1\0\10\6\1\0"+
    "\3\6\1\0\27\6\1\0\12\6\1\0\5\6\2\0\1\0\1\6"+
    "\7\0\1\0\3\0\1\0\4\0\7\0\2\0\7\0\1\6\1\0"+
    "\2\6\4\0\12\0\22\0\2\0\1\0\10\6\1\0\3\6\1\0"+
    "\27\6\1\0\20\6\4\0\6\0\2\0\3\0\1\0\4\0\11\0"+
    "\1\0\10\0\2\6\4\0\12\0\22\0\2\0\1\0\22\6\3\0"+
    "\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\0\4\0"+
    "\6\0\1\0\1\0\1\0\10\0\22\0\2\0\15\0\60\6\1\0"+
    "\2\6\7\0\4\0\1\0\7\6\10\0\1\0\12\0\47\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6"+
    "\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6"+
    "\1\0\4\6\1\0\2\6\6\0\1\0\2\0\1\6\2\0\5\6"+
    "\1\0\1\6\1\0\6\0\2\0\12\0\2\0\2\6\42\0\1\6"+
    "\27\0\2\0\6\0\12\0\13\0\1\0\1\0\1\0\1\0\1\0"+
    "\4\0\2\0\10\6\1\0\42\6\6\0\24\0\1\0\2\0\4\6"+
    "\4\0\10\0\1\0\44\0\11\0\1\0\71\0\42\6\1\0\5\6"+
    "\1\0\2\6\1\0\7\0\3\0\4\0\6\0\12\0\6\0\6\6"+
    "\4\0\106\0\46\6\12\0\51\6\7\0\132\6\5\0\104\6\5\0"+
    "\122\6\6\0\7\6\1\0\77\6\1\0\1\6\1\0\4\6\2\0"+
    "\7\6\1\0\1\6\1\0\4\6\2\0\47\6\1\0\1\6\1\0"+
    "\4\6\2\0\37\6\1\0\1\6\1\0\4\6\2\0\7\6\1\0"+
    "\1\6\1\0\4\6\2\0\7\6\1\0\7\6\1\0\27\6\1\0"+
    "\37\6\1\0\1\6\1\0\4\6\2\0\7\6\1\0\47\6\1\0"+
    "\23\6\16\0\11\0\56\0\125\6\14\0\u026c\6\2\0\10\6\12\0"+
    "\32\6\5\0\113\6\3\0\3\0\17\0\15\6\1\0\4\6\3\0"+
    "\13\0\22\6\3\0\13\0\22\6\2\0\14\0\15\6\1\0\3\6"+
    "\1\0\2\0\14\0\64\6\40\0\3\0\1\6\3\0\1\0\1\6"+
    "\1\0\2\0\12\0\41\0\3\0\2\0\12\0\6\0\130\6\10\0"+
    "\51\6\1\0\126\0\35\6\3\0\14\0\4\0\14\0\12\0\12\0"+
    "\36\6\2\0\5\6\u038b\0\154\6\224\0\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\7\6\4\0\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\6\0\10\6\10\6"+
    "\6\6\2\0\6\6\2\0\10\6\10\6\10\6\10\6\6\6\2\0"+
    "\6\6\2\0\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\1\6\10\6\10\6\16\6\2\0\65\6\1\0\2\6\4\6\1\6"+
    "\1\0\1\6\3\0\3\6\1\0\2\6\4\6\1\6\3\0\4\6"+
    "\2\0\2\6\4\6\4\0\10\6\5\6\5\0\3\6\1\0\2\6"+
    "\4\6\1\6\17\0\4\0\32\0\5\0\20\0\2\0\23\0\1\0"+
    "\13\0\4\0\6\0\6\0\1\0\1\6\15\0\1\6\40\0\22\0"+
    "\36\0\15\0\4\0\1\0\3\0\6\0\27\0\1\6\4\0\1\6"+
    "\2\0\1\6\3\6\2\6\3\6\1\6\1\0\1\6\3\0\5\6"+
    "\6\0\1\6\1\0\1\6\1\0\1\6\1\0\4\6\1\0\1\6"+
    "\2\6\1\0\1\6\6\6\3\0\1\6\2\6\5\0\1\6\4\6"+
    "\26\0\44\0\u0e81\0\2\6\1\0\31\0\17\0\1\0\5\6\2\0"+
    "\3\0\2\6\4\0\126\6\2\0\2\0\2\0\3\6\1\0\132\6"+
    "\1\0\4\6\5\0\50\6\4\0\136\6\21\0\30\6\70\0\20\6"+
    "\u0200\0\u19b6\6\112\0\u51a6\6\132\0\u048d\6\u0773\0\u2ba4\6\u215c\0\u012e\6"+
    "\2\0\73\6\225\0\7\6\14\0\5\6\5\0\1\6\1\0\12\6"+
    "\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6"+
    "\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\14\6"+
    "\1\0\3\0\20\0\20\0\4\0\17\0\2\0\30\0\3\0\31\0"+
    "\1\0\6\0\5\6\1\0\207\6\2\0\1\0\4\0\1\0\13\0"+
    "\12\0\7\0\32\6\4\0\1\0\1\0\32\6\12\0\1\0\131\6"+
    "\3\0\6\6\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\0"+
    "\3\0\2\0\22\0\3\0\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\1\1\5\1\6";

  private static int [] zzUnpackAction() {
    int [] result = new int[11];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\7\0\16\0\25\0\25\0\34\0\43\0\52"+
    "\0\61\0\70\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[11];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\3\4\1\5\1\6"+
    "\1\7\1\10\1\11\2\4\1\5\1\6\1\12\3\4"+
    "\10\0\1\5\10\0\1\7\3\0\1\10\2\0\4\10"+
    "\6\0\1\13\3\0\1\12\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[11];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  NSISLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  NSISLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch ((zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL-1] : zzBufferL.charAt(zzMarkedPosL-1))) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { yybegin(YYINITIAL); return NSISTypes.CRLF;
          }
        case 7: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 8: break;
        case 4: 
          { yybegin(YYINITIAL); return NSISTypes.COMMENT;
          }
        case 9: break;
        case 3: 
          { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
          }
        case 10: break;
        case 6: 
          { yybegin(YYINITIAL); return NSISTypes.COMPILE_COMMAND;
          }
        case 11: break;
        case 5: 
          { yybegin(WAITING_VALUE); return TokenType.WHITE_SPACE;
          }
        case 12: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
