{
  parserClass="com.jotc.nsis.parser.NSISParser"
  parserUtilClass="com.jotc.nsis.parser.NSISParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="NSIS"
  psiImplClassSuffix="Impl"
  psiPackage="com.jotc.nsis.psi"
  psiImplPackage="com.jotc.nsis.psi.impl"

  elementTypeHolderClass="com.jotc.nsis.psi.NSISTypes"
  elementTypeClass="com.jotc.nsis.psi.NSISElementType"
  tokenTypeClass="com.jotc.nsis.psi.NSISTokenType"

  psiImplUtilClass="com.jotc.nsis.psi.impl.NSISPsiImplUtil"
}

nsisFile ::= item_*

private item_ ::= (IDENTIFIER|NUMBER|VARIABLE|CONSTANT|SPECIAL_SYMBOL|VALUE|STRING|PLUGIN_CALL|INSTRUCTION|BLOCK_DECLARATION|KEYWORD|COMPILER_COMMAND|COMMENT|CRLF|WHITE_SPACE)